import { Platform, StatusBar, StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F3F4F8',
    paddingTop: Platform.OS === 'android' ? (StatusBar.currentHeight || 0) : 0,
  },
  scrollContent: {
    padding: 20,
    paddingBottom: 40,
  },
  homeContainer: {
    flex: 1,
  },
  homeScrollContent: {
    padding: 20,
    paddingBottom: 24,
  },
  homeBottomNavWrapper: {
    paddingHorizontal: 14,
    paddingBottom: 14,
    backgroundColor: '#F3F4F8',
  },
  homeHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 22,
  },
  homeBrand: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  homeBrandIcon: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: '#E2E8F0',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  homeBrandText: {
    color: '#0F172A',
    fontSize: 18,
    fontWeight: '800',
  },
  notificationButton: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 5 },
  },
  homeGreeting: {
    color: '#475569',
    fontSize: 14,
    marginBottom: 4,
  },
  homeTitle: {
    fontSize: 28,
    fontWeight: '800',
    color: '#0F172A',
    marginBottom: 20,
  },
  vehicleListContainer: {
    flex: 1,
  },
  vehicleListScrollContent: {
    padding: 20,
    paddingBottom: 28,
  },
  vehicleListHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 18,
  },
  vehicleListBackButton: {
    width: 42,
    height: 42,
    borderRadius: 12,
    backgroundColor: 'rgba(15, 23, 42, 0.06)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  vehicleListBackButtonSpacer: {
    width: 42,
    height: 42,
  },
  vehicleListHeaderTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: '#0F172A',
  },
  vehicleListHero: {
    marginBottom: 20,
  },
  vehicleListTitle: {
    fontSize: 32,
    fontWeight: '800',
    color: '#0F172A',
    marginBottom: 8,
  },
  vehicleListSubtitle: {
    color: '#475569',
    fontSize: 15,
    lineHeight: 22,
  },
  vehicleListLoadingCard: {
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    paddingVertical: 18,
    marginBottom: 18,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
  },
  vehicleListLoadingText: {
    textAlign: 'center',
    color: '#64748B',
    fontSize: 14,
    fontWeight: '600',
  },
  vehicleListErrorText: {
    textAlign: 'center',
    color: '#EF4444',
    fontSize: 14,
    fontWeight: '600',
  },
  vehicleListCard: {
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    overflow: 'hidden',
    marginBottom: 18,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 6 },
  },
  vehicleListImage: {
    width: '100%',
    height: 190,
    justifyContent: 'flex-start',
    alignItems: 'flex-end',
  },
  vehicleListImageOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(15, 23, 42, 0.18)',
  },
  vehicleListMenuButton: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: 'rgba(15, 23, 42, 0.6)',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
    marginRight: 10,
  },
  vehicleListContent: {
    padding: 18,
  },
  vehicleListTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  vehicleListYear: {
    fontSize: 18,
    fontWeight: '700',
    color: '#0F172A',
  },
  vehicleListStatusBadge: {
    backgroundColor: '#E7F8ED',
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 999,
  },
  vehicleListStatusText: {
    color: '#15803D',
    fontSize: 12,
    fontWeight: '800',
  },
  vehicleListName: {
    fontSize: 20,
    fontWeight: '800',
    color: '#0F172A',
    marginBottom: 12,
  },
  vehicleListMetaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 14,
  },
  vehicleListMetaItem: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  vehicleListMetaText: {
    marginLeft: 6,
    fontSize: 13,
    color: '#475569',
    fontWeight: '500',
  },
  vehicleListAddCard: {
    borderRadius: 18,
    backgroundColor: '#1E293B',
    paddingVertical: 30,
    paddingHorizontal: 24,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 18,
  },
  vehicleListAddIconWrap: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  vehicleListAddTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#FFFFFF',
    marginBottom: 6,
    textAlign: 'center',
  },
  vehicleListAddSubtitle: {
    fontSize: 13,
    color: '#CBD5E1',
    textAlign: 'center',
    lineHeight: 18,
  },
  card: {
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    overflow: 'hidden',
    marginBottom: 20,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
  },
  cardImage: {
    width: '100%',
    height: 190,
    justifyContent: 'flex-end',
  },
  cardOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(15, 23, 42, 0.25)',
  },
  cardStatus: {
    backgroundColor: 'rgba(15, 23, 42, 0.85)',
    alignSelf: 'flex-start',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
    margin: 14,
  },
  cardStatusText: {
    color: '#F8FAFC',
    fontSize: 12,
    fontWeight: '700',
  },
  cardBody: {
    padding: 18,
  },
  cardRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 18,
  },
  cardTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#0F172A',
  },
  cardSubtitle: {
    color: '#64748B',
    marginTop: 4,
    fontSize: 13,
  },
  cardCost: {
    alignItems: 'flex-end',
  },
  cardCostLabel: {
    color: '#94A3B8',
    fontSize: 10,
    letterSpacing: 0.4,
  },
  cardCostValue: {
    color: '#0F172A',
    fontSize: 20,
    fontWeight: '800',
  },
  progressRow: {
    flexDirection: 'row',
    height: 6,
    borderRadius: 999,
    overflow: 'hidden',
    marginBottom: 14,
  },
  progressSegment: {
    flex: 1,
  },
  progressActive: {
    backgroundColor: '#0F172A',
  },
  progressInactive: {
    backgroundColor: '#E2E8F0',
  },
  statusRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 18,
  },
  statusItem: {
    alignItems: 'center',
  },
  statusLabel: {
    marginTop: 6,
    fontSize: 11,
    color: '#0F172A',
    fontWeight: '700',
  },
  statusLabelActive: {
    marginTop: 6,
    fontSize: 11,
    color: '#0F172A',
    fontWeight: '700',
  },
  statusLabelInactive: {
    marginTop: 6,
    fontSize: 11,
    color: '#94A3B8',
    fontWeight: '700',
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#0F172A',
    marginBottom: 14,
  },
  quickActionsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  actionCard: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    padding: 16,
    alignItems: 'flex-start',
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 10 },
    marginRight: 12,
  },
  actionIcon: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: '#E2E8F0',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  actionTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#0F172A',
    marginBottom: 4,
  },
  actionSubtitle: {
    fontSize: 12,
    color: '#64748B',
  },
  shopCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#0F172A',
    borderRadius: 18,
    padding: 18,
    marginTop: 18,
  },
  shopName: {
    color: '#FFFFFF',
    fontSize: 17,
    fontWeight: '800',
  },
  shopSubtitle: {
    color: 'rgba(255, 255, 255, 0.75)',
    fontSize: 13,
    marginTop: 2,
  },
  shopMeta: {
    color: 'rgba(255, 255, 255, 0.7)',
    fontSize: 12,
    marginTop: 6,
  },
  callButton: {
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 18,
    paddingVertical: 12,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
  },
  callButtonText: {
    color: '#0F172A',
    fontWeight: '800',
  },
  bottomNav: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 10,
    paddingHorizontal: 4,
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#DCE3ED',
  },
  navItem: {
    flex: 1,
    minHeight: 72,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  navItemSelected: {
    backgroundColor: '#E8EDF4',
  },
  navLabel: {
    marginTop: 5,
    fontSize: 12,
    color: '#8A9DB7',
    fontWeight: '500',
  },
  navLabelActive: {
    color: '#0F172A',
    fontWeight: '700',
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  backButton: {
    padding: 10,
    borderRadius: 12,
    backgroundColor: 'rgba(15, 23, 42, 0.06)',
  },
  backButtonPlaceholder: {
    width: 42,
    height: 42,
  },
  headerTitleLarge: {
    fontSize: 22,
    fontWeight: '800',
    color: '#0F172A',
    textAlign: 'center',
  },
  pageTitle: {
    fontSize: 32,
    fontWeight: '800',
    color: '#0F172A',
    marginTop: 8,
  },
  pageSubtitle: {
    fontSize: 15,
    color: '#475569',
    marginTop: 6,
    marginBottom: 24,
    lineHeight: 22,
  },
  keyboardWrapper: {
    flex: 1,
  },
  headerCard: {
    borderRadius: 18,
    overflow: 'hidden',
    marginBottom: 28,
    backgroundColor: '#111827',
    elevation: 6,
    shadowColor: '#000',
    shadowOpacity: 0.12,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
  },
  headerImage: {
    width: '100%',
    height: 200,
    justifyContent: 'flex-end',
  },
  headerOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(15, 23, 42, 0.35)',
  },
  headerText: {
    padding: 18,
  },
  headerTitle: {
    color: '#F8FAFC',
    fontSize: 22,
    fontWeight: '700',
  },
  headerSubtitle: {
    color: 'rgba(241, 245, 249, 0.85)',
    marginTop: 4,
    fontSize: 14,
  },
  form: {
    paddingBottom: 32,
  },
  subtitleText: {
    fontSize: 15,
    color: '#475569',
    marginBottom: 18,
    lineHeight: 22,
  },
  rowGroup: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 18,
  },
  halfField: {
    flex: 1,
  },
  halfFieldSpacing: {
    marginRight: 12,
  },
  fieldGroup: {
    marginBottom: 18,
  },
  fieldLabel: {
    fontSize: 14,
    color: '#1F2937',
    marginBottom: 10,
    fontWeight: '600',
  },
  fieldLabelRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  forgotText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#0F172A',
  },
  input: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 14,
    fontSize: 16,
    color: '#0F172A',
    shadowColor: '#000',
    shadowOpacity: 0.03,
    shadowRadius: 5,
    shadowOffset: { width: 0, height: 2 },
  },
  inputWithIcon: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 14,
    shadowColor: '#000',
    shadowOpacity: 0.03,
    shadowRadius: 5,
    shadowOffset: { width: 0, height: 2 },
  },
  inputIcon: {
    marginRight: 12,
  },
  inputWithIconField: {
    flex: 1,
    fontSize: 16,
    color: '#0F172A',
    padding: 0,
  },
  passwordRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  passwordInputWrapper: {
    flex: 1,
  },
  eyeButton: {
    marginLeft: -44,
    padding: 12,
  },
  eyeButtonRegister: {
    marginLeft: 12,
    padding: 14,
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    shadowColor: '#000',
    shadowOpacity: 0.03,
    shadowRadius: 5,
    shadowOffset: { width: 0, height: 2 },
  },
  primaryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#0F172A',
    borderRadius: 14,
    paddingVertical: 16,
    marginTop: 8,
    shadowColor: '#0F172A',
    shadowOpacity: 0.18,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
  },
  buttonIcon: {
    marginLeft: 10,
  },
  dividerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 24,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: '#CBD5E1',
  },
  dividerText: {
    marginHorizontal: 12,
    color: '#64748B',
    fontWeight: '600',
    fontSize: 13,
  },
  socialRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 18,
  },
  socialButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 14,
    paddingVertical: 14,
    marginHorizontal: 4,
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
  },
  socialIcon: {
    marginRight: 10,
  },
  socialText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#1F2937',
  },
  bottomRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 28,
  },
  bottomRowRegister: {
    marginTop: 18,
  },
  bottomText: {
    color: '#64748B',
    fontSize: 14,
  },
  bottomLink: {
    color: '#0F172A',
    fontSize: 14,
    fontWeight: '700',
  },
  termsText: {
    color: '#64748B',
    fontSize: 13,
    textAlign: 'center',
    marginTop: 16,
    lineHeight: 20,
  },
  linkText: {
    color: '#0F172A',
    fontWeight: '700',
  },
  verifyContainer: {
    flex: 1,
    minHeight: 700,
    paddingTop: 4,
  },
  verifyHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  verifyBackButton: {
    width: 44,
    height: 44,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
  },
  verifyHeaderTitle: {
    flex: 1,
    fontSize: 22,
    fontWeight: '800',
    color: '#0B1A37',
    textAlign: 'left',
    marginLeft: 8,
  },
  verifyHeaderSpacer: {
    width: 44,
    height: 44,
  },
  verifyDivider: {
    height: 1,
    backgroundColor: '#E2E8F0',
    marginHorizontal: -20,
    marginBottom: 48,
  },
  verifyTitle: {
    fontSize: 56,
    lineHeight: 58,
    fontWeight: '800',
    color: '#0B1A37',
    marginBottom: 14,
  },
  verifySubtitle: {
    fontSize: 17,
    lineHeight: 33,
    color: '#334155',
    marginBottom: 8,
  },
  verifyTenantMeta: {
    fontSize: 14,
    color: '#64748B',
    marginBottom: 36,
    fontWeight: '600',
  },
  otpBoxesRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 46,
  },
  otpCell: {
    width: 54,
    height: 72,
    borderWidth: 1,
    borderColor: '#D8DEE7',
    borderRadius: 14,
    backgroundColor: '#F8FAFC',
    alignItems: 'center',
    justifyContent: 'center',
  },
  otpCellFocused: {
    borderColor: '#0B1A37',
  },
  otpCellFilled: {
    backgroundColor: '#FFFFFF',
  },
  otpCellText: {
    fontSize: 26,
    fontWeight: '700',
    color: '#0B1A37',
  },
  otpHiddenInput: {
    position: 'absolute',
    width: 1,
    height: 1,
    opacity: 0,
  },
  verifyButton: {
    backgroundColor: '#132B46',
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 22,
    marginBottom: 34,
    shadowColor: '#102B45',
    shadowOpacity: 0.2,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
  },
  verifyButtonText: {
    color: '#FFFFFF',
    fontSize: 22,
    fontWeight: '800',
  },
  verifyResendLabel: {
    textAlign: 'center',
    color: '#334155',
    fontSize: 17,
    marginBottom: 8,
  },
  verifyResendLink: {
    textAlign: 'center',
    color: '#0B1A37',
    fontSize: 20,
    fontWeight: '800',
    textDecorationLine: 'underline',
  },
  profileContainer: {
    flex: 1,
    backgroundColor: '#F4F6FA',
  },
  profileScrollContent: {
    paddingTop: 8,
    paddingHorizontal: 20,
    paddingBottom: 24,
  },
  profileHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  profileBackButton: {
    width: 42,
    height: 42,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileBackButtonSpacer: {
    width: 42,
    height: 42,
  },
  profileHeaderTitle: {
    fontSize: 28,
    fontWeight: '800',
    color: '#0F1F3A',
    letterSpacing: 0.1,
  },
  profileDivider: {
    marginHorizontal: -20,
    marginBottom: 18,
    height: 1,
    backgroundColor: '#E5EAF2',
  },
  profileIdentitySection: {
    alignItems: 'center',
    marginBottom: 24,
  },
  profileAvatarWrap: {
    width: 118,
    height: 118,
    borderRadius: 59,
    padding: 4,
    backgroundColor: '#E8EDF4',
    marginBottom: 12,
  },
  profileAvatar: {
    width: '100%',
    height: '100%',
    borderRadius: 55,
    backgroundColor: '#D8DEE7',
  },
  profileAvatarEdit: {
    position: 'absolute',
    right: -2,
    bottom: 6,
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#0F1F3A',
    borderWidth: 2,
    borderColor: '#F4F6FA',
  },
  profileName: {
    fontSize: 24,
    fontWeight: '800',
    color: '#0F1F3A',
    marginBottom: 2,
  },
  profileMembershipRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
  },
  profileMembershipText: {
    marginLeft: 8,
    color: '#344968',
    fontSize: 15,
    fontWeight: '500',
  },
  profileMeta: {
    color: '#8B9CB4',
    fontSize: 13,
    fontWeight: '500',
  },
  profileSectionHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  profileSectionTitle: {
    color: '#0F1F3A',
    fontSize: 14,
    fontWeight: '800',
    letterSpacing: 1.2,
    marginBottom: 12,
  },
  profileAddNewButton: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  profileVehicleHeaderActions: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  profileVehiclesRefreshButton: {
    width: 30,
    height: 30,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#E8EDF4',
    marginLeft: 8,
  },
  profileAddNewText: {
    marginLeft: 5,
    color: '#0F1F3A',
    fontSize: 13,
    fontWeight: '700',
  },
  profileVehicleCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#EEF2F7',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    padding: 14,
    marginBottom: 12,
  },
  profileVehicleIconWrap: {
    width: 50,
    height: 50,
    borderRadius: 11,
    backgroundColor: '#DCE2EA',
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileVehicleTextWrap: {
    flex: 1,
    marginLeft: 14,
    marginRight: 8,
  },
  profileVehicleTitle: {
    color: '#0F1F3A',
    fontSize: 16,
    fontWeight: '800',
    marginBottom: 2,
  },
  profileVehicleMeta: {
    color: '#60708A',
    fontSize: 13,
    fontWeight: '500',
  },
  profileListCard: {
    backgroundColor: '#F8FAFD',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#DDE4EE',
    marginBottom: 18,
    overflow: 'hidden',
  },
  profileListRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    minHeight: 66,
    paddingHorizontal: 16,
    backgroundColor: '#F8FAFD',
  },
  profileListRowBorder: {
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
  },
  profileListLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  profileListLabel: {
    color: '#0F1F3A',
    fontSize: 15,
    fontWeight: '500',
    marginLeft: 12,
  },
  profileLogoutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#E8ECF2',
    minHeight: 62,
    borderRadius: 14,
    marginTop: 4,
  },
  profileLogoutText: {
    color: '#E11D48',
    fontSize: 16,
    fontWeight: '700',
    marginLeft: 8,
  },
  profileVersionText: {
    marginTop: 20,
    marginBottom: 2,
    textAlign: 'center',
    fontSize: 12,
    color: '#8B9CB4',
    fontWeight: '500',
  },
  personalInfoContainer: {
    flex: 1,
    backgroundColor: '#F4F6FA',
  },
  personalInfoScrollContent: {
    paddingTop: 8,
    paddingHorizontal: 20,
    paddingBottom: 16,
  },
  personalInfoHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  personalInfoBackButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: -2,
  },
  personalInfoHeaderTitle: {
    flex: 1,
    marginLeft: 10,
    color: '#0F1F3A',
    fontSize: 19,
    fontWeight: '800',
  },
  personalInfoInfoButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#A3AAB4',
  },
  personalInfoDivider: {
    marginHorizontal: -20,
    marginBottom: 18,
    height: 1,
    backgroundColor: '#E4EAF2',
  },
  personalInfoIdentitySection: {
    alignItems: 'center',
    marginBottom: 20,
  },
  personalInfoAvatarWrap: {
    width: 124,
    height: 124,
    borderRadius: 62,
    padding: 4,
    backgroundColor: '#E5EBF3',
    marginBottom: 14,
  },
  personalInfoAvatar: {
    width: '100%',
    height: '100%',
    borderRadius: 74,
    backgroundColor: '#CDD5E1',
  },
  personalInfoAvatarEdit: {
    position: 'absolute',
    right: -3,
    bottom: 8,
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#0F233E',
    borderWidth: 2,
    borderColor: '#F4F6FA',
  },
  personalInfoName: {
    color: '#0C1730',
    fontSize: 22,
    fontWeight: '800',
    marginBottom: 2,
  },
  personalInfoMemberMeta: {
    color: '#5A6D88',
    fontSize: 13,
    fontWeight: '500',
  },
  personalInfoFieldGroup: {
    marginBottom: 12,
  },
  personalInfoFieldGroupLast: {
    marginBottom: 8,
  },
  personalInfoFieldLabel: {
    color: '#243851',
    fontSize: 12,
    fontWeight: '700',
    marginBottom: 8,
    marginLeft: 4,
  },
  personalInfoFieldCard: {
    minHeight: 70,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#CED8E6',
    backgroundColor: '#E8EDF3',
    paddingHorizontal: 18,
    paddingVertical: 14,
    flexDirection: 'row',
    alignItems: 'center',
  },
  personalInfoFieldCardLarge: {
    minHeight: 128,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#CED8E6',
    backgroundColor: '#E8EDF3',
    paddingHorizontal: 18,
    paddingVertical: 16,
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  personalInfoLocationIcon: {
    marginTop: 2,
  },
  personalInfoFieldValue: {
    flex: 1,
    marginLeft: 14,
    color: '#101927',
    fontSize: 13,
    fontWeight: '500',
  },
  personalInfoFieldValueAddress: {
    flex: 1,
    marginLeft: 14,
    color: '#101927',
    fontSize: 13,
    fontWeight: '500',
    lineHeight: 22,
  },
  personalInfoFooter: {
    borderTopWidth: 1,
    borderTopColor: '#E2E8F0',
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 14,
    backgroundColor: '#F4F6FA',
  },
  personalInfoSaveButton: {
    minHeight: 58,
    borderRadius: 14,
    backgroundColor: '#122B49',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    shadowColor: '#0A1A30',
    shadowOpacity: 0.2,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
  },
  personalInfoSaveButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '800',
    marginLeft: 8,
  },
  personalInfoUpdatedText: {
    textAlign: 'center',
    marginTop: 10,
    color: '#8696AD',
    fontSize: 12,
    fontWeight: '500',
  },
  addVehicleContainer: {
    flex: 1,
    backgroundColor: '#F4F6FA',
  },
  addVehicleScrollContent: {
    paddingTop: 8,
    paddingHorizontal: 18,
    paddingBottom: 22,
  },
  addVehicleHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  addVehicleBackButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addVehicleHeaderTitle: {
    flex: 1,
    marginLeft: 6,
    color: '#0F1F3A',
    fontSize: 17,
    fontWeight: '800',
  },
  addVehicleHeaderSpacer: {
    width: 40,
    height: 40,
  },
  addVehicleDivider: {
    marginHorizontal: -18,
    marginBottom: 14,
    height: 1,
    backgroundColor: '#E3E8F0',
  },
  addVehicleFieldLabel: {
    color: '#131F33',
    fontSize: 11,
    fontWeight: '700',
    marginBottom: 8,
    marginLeft: 4,
    marginTop: 8,
  },
  addVehicleInput: {
    minHeight: 50,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#CED7E3',
    backgroundColor: '#F6F8FB',
    paddingHorizontal: 16,
    fontSize: 16,
    color: '#152238',
  },
  addVehicleSelectRow: {
    minHeight: 50,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#CED7E3',
    backgroundColor: '#F6F8FB',
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
  },
  addVehicleSelectText: {
    color: '#152238',
    fontSize: 16,
    fontWeight: '500',
  },
  addVehicleSelectPlaceholder: {
    color: '#8A9AB0',
  },
  addVehicleSelectRowDisabled: {
    opacity: 0.7,
  },
  addVehicleVinWrap: {
    minHeight: 40,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#CED7E3',
    backgroundColor: '#F6F8FB',
    overflow: 'hidden',
    flexDirection: 'row',
    alignItems: 'center',
  },
  addVehicleVinInput: {
    flex: 1,
    paddingHorizontal: 12,
    fontSize: 14,
    color: '#152238',
  },
  addVehicleVinScanButton: {
    width: 48,
    height: '100%',
    backgroundColor: '#E4E8EE',
    alignItems: 'center',
    justifyContent: 'center',
  },
  addVehicleInfoCard: {
    marginTop: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E1E6EE',
    backgroundColor: '#EDF1F6',
    padding: 14,
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  addVehicleInfoIcon: {
    marginRight: 10,
    marginTop: 1,
  },
  addVehicleInfoText: {
    flex: 1,
    color: '#566981',
    fontSize: 12,
    lineHeight: 22,
    fontWeight: '500',
  },
  addVehicleFooter: {
    paddingHorizontal: 18,
    paddingTop: 12,
    paddingBottom: 16,
    borderTopWidth: 1,
    borderTopColor: '#E3E8F0',
    backgroundColor: '#F4F6FA',
  },
  addVehicleSaveButton: {
    minHeight: 62,
    borderRadius: 14,
    backgroundColor: '#132B49',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#0A1A30',
    shadowOpacity: 0.2,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
  },
  addVehicleSaveButtonDisabled: {
    opacity: 0.55,
  },
  addVehicleSaveButtonText: {
    color: '#FFFFFF',
    fontSize: 17,
    fontWeight: '800',
  },
  addVehicleDropdownOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.38)',
    justifyContent: 'center',
    paddingHorizontal: 22,
  },
  addVehicleDropdownCard: {
    maxHeight: '70%',
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D7E0EC',
    paddingVertical: 12,
  },
  addVehicleDropdownTitle: {
    color: '#0F1F3A',
    fontSize: 16,
    fontWeight: '800',
    paddingHorizontal: 16,
    marginBottom: 10,
  },
  addVehicleDropdownList: {
    paddingHorizontal: 8,
  },
  addVehicleDropdownItem: {
    minHeight: 46,
    borderRadius: 10,
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  addVehicleDropdownItemText: {
    color: '#1D2A3E',
    fontSize: 15,
    fontWeight: '500',
  },
  bookServiceContainer: {
    flex: 1,
    backgroundColor: '#F4F6FA',
  },
  bookServiceScrollContent: {
    paddingTop: 8,
    paddingHorizontal: 22,
    paddingBottom: 30,
  },
  bookServiceHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  bookServiceBackButton: {
    width: 42,
    height: 42,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bookServiceHeaderTitle: {
    flex: 1,
    marginLeft: 12,
    color: '#0F1F3A',
    fontSize: 24,
    fontWeight: '800',
  },
  bookServiceMoreButton: {
    width: 42,
    height: 42,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bookServiceDivider: {
    marginHorizontal: -22,
    marginBottom: 22,
    height: 1,
    backgroundColor: '#E5EAF2',
  },
  bookServiceStepRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  bookServiceStepRowStepTwo: {
    marginBottom: 4,
  },
  bookServiceStepText: {
    fontSize: 16,
    color: '#243850',
    fontWeight: '500',
    letterSpacing: 1,
  },
  bookServiceStepTitle: {
    color: '#0F1F3A',
    fontSize: 44,
    fontWeight: '800',
    marginBottom: 14,
  },
  bookServiceStepPercent: {
    color: '#0F1F3A',
    fontSize: 20,
    fontWeight: '800',
  },
  bookServiceProgressTrack: {
    width: '100%',
    height: 8,
    borderRadius: 999,
    backgroundColor: '#E6EAF0',
    marginBottom: 28,
    overflow: 'hidden',
  },
  bookServiceProgressFill: {
    width: '33%',
    height: '100%',
    backgroundColor: '#11243C',
    borderRadius: 999,
  },
  bookServiceProgressSegmentsRow: {
    flexDirection: 'row',
    gap: 6,
    marginBottom: 22,
  },
  bookServiceProgressSegment: {
    flex: 1,
    height: 7,
    borderRadius: 999,
    backgroundColor: '#E6EAF0',
  },
  bookServiceProgressSegmentActive: {
    backgroundColor: '#11243C',
  },
  bookServiceCalendarCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#DEE5EE',
    padding: 16,
    marginBottom: 20,
  },
  bookServiceCalendarHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  bookServiceCalendarMonth: {
    color: '#0F1F3A',
    fontSize: 18,
    fontWeight: '700',
  },
  bookServiceCalendarArrows: {
    flexDirection: 'row',
  },
  bookServiceCalendarArrowButton: {
    width: 28,
    height: 28,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 6,
  },
  bookServiceCalendarWeekRow: {
    flexDirection: 'row',
    marginBottom: 8,
  },
  bookServiceCalendarWeekDay: {
    width: '14.28%',
    textAlign: 'center',
    color: '#42546D',
    fontSize: 13,
    fontWeight: '600',
    marginBottom: 4,
  },
  bookServiceCalendarDaysGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  bookServiceCalendarCell: {
    width: '14.28%',
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 4,
    minHeight: 40,
    borderRadius: 10,
  },
  bookServiceCalendarCellSelected: {
    backgroundColor: '#12263F',
  },
  bookServiceCalendarDay: {
    color: '#0F1F3A',
    fontSize: 16,
    fontWeight: '500',
  },
  bookServiceCalendarDaySelected: {
    color: '#FFFFFF',
    fontWeight: '700',
  },
  bookServiceCalendarDayMuted: {
    color: '#B5C1D0',
    fontSize: 16,
    fontWeight: '500',
  },
  bookServiceInfoHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  bookServiceInfoTitle: {
    marginLeft: 10,
    color: '#0F1F3A',
    fontSize: 18,
    fontWeight: '800',
  },
  bookServiceTimeSlotsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  bookServiceTimeSlot: {
    width: '48.3%',
    minHeight: 62,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#CFD9E6',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
  },
  bookServiceTimeSlotSelected: {
    backgroundColor: '#12263F',
    borderColor: '#12263F',
  },
  bookServiceTimeSlotDisabled: {
    backgroundColor: '#F4F6FA',
    borderColor: '#E2E8F0',
  },
  bookServiceTimeSlotText: {
    color: '#0F1F3A',
    fontSize: 18,
    fontWeight: '700',
  },
  bookServiceTimeSlotTextSelected: {
    color: '#FFFFFF',
  },
  bookServiceTimeSlotTextDisabled: {
    color: '#9AA5B5',
  },
  bookServiceNotesInput: {
    minHeight: 128,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#CFD9E6',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 16,
    color: '#0F1F3A',
    marginBottom: 18,
  },
  bookServiceDurationText: {
    textAlign: 'center',
    color: '#334A66',
    fontSize: 14,
    marginTop: 12,
    marginBottom: 8,
  },
  bookServiceSectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 14,
  },
  bookServiceSectionTitle: {
    color: '#0F1F3A',
    fontSize: 18,
    fontWeight: '800',
    marginBottom: 14,
  },
  bookServiceAddNew: {
    color: '#0F1F3A',
    fontSize: 14,
    fontWeight: '700',
    textDecorationLine: 'underline',
  },
  bookServiceVehicleList: {
    paddingBottom: 30,
  },
  bookServiceVehicleCard: {
    width: 320,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: '#E1E7F0',
    backgroundColor: '#F9FAFC',
    padding: 18,
    marginRight: 14,
  },
  bookServiceVehicleCardSelected: {
    borderColor: '#0F1F3A',
  },
  bookServiceVehicleTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 14,
  },
  bookServiceVehicleIconWrap: {
    width: 64,
    height: 64,
    borderRadius: 14,
    backgroundColor: '#ECEFF5',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bookServiceVehicleCheck: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#11243C',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bookServiceVehicleName: {
    color: '#0F1F3A',
    fontSize: 16,
    fontWeight: '500',
    marginBottom: 6,
  },
  bookServiceVehicleModel: {
    color: '#0F1F3A',
    fontSize: 16,
    fontWeight: '800',
    marginBottom: 6,
  },
  bookServiceVehicleLicense: {
    color: '#334A66',
    fontSize: 15,
    fontWeight: '500',
  },
  bookServiceServiceCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 20,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 14,
  },
  bookServiceCheckBox: {
    width: 30,
    height: 30,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#C9D3E2',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F8FAFC',
  },
  bookServiceCheckBoxSelected: {
    backgroundColor: '#11243C',
    borderColor: '#11243C',
  },
  bookServiceServiceTextWrap: {
    flex: 1,
    marginLeft: 12,
    marginRight: 10,
  },
  bookServiceServiceTitle: {
    color: '#0F1F3A',
    fontSize: 15,
    fontWeight: '800',
    marginBottom: 4,
  },
  bookServiceServiceDescription: {
    color: '#334A66',
    fontSize: 13,
    fontWeight: '500',
  },
  bookServiceServicePrice: {
    color: '#0F1F3A',
    fontSize: 18,
    fontWeight: '800',
  },
  bookServiceTotalCard: {
    marginTop: 8,
    marginBottom: 14,
    backgroundColor: '#12263F',
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 18,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  bookServiceTotalLabel: {
    color: 'rgba(183, 204, 229, 0.9)',
    fontSize: 12,
    letterSpacing: 1.2,
    fontWeight: '500',
    marginBottom: 4,
  },
  bookServiceTotalValue: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '800',
  },
  bookServiceTotalMetaWrap: {
    alignItems: 'flex-end',
  },
  bookServiceTotalMeta: {
    color: '#E8EEF8',
    fontSize: 18,
    fontWeight: '600',
    marginBottom: 2,
  },
  bookServiceTotalSubMeta: {
    color: 'rgba(211, 223, 239, 0.82)',
    fontSize: 13,
    fontWeight: '500',
  },
  bookServiceNextButton: {
    minHeight: 72,
    borderRadius: 18,
    backgroundColor: '#12263F',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  bookServiceNextButtonText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '700',
  },
  bookServiceNextIcon: {
    marginLeft: 10,
  },
  bookServicePendingIconOuter: {
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: '#E9EEF5',
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
    marginBottom: 16,
  },
  bookServicePendingIconInner: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#4A607A',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bookServicePendingTitle: {
    textAlign: 'center',
    color: '#0F1F3A',
    fontSize: 30,
    fontWeight: '800',
    marginBottom: 8,
  },
  bookServicePendingSubtitle: {
    textAlign: 'center',
    color: '#2E4460',
    fontSize: 16,
    lineHeight: 26,
    marginBottom: 18,
  },
  bookServiceConfirmCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#D8E0EB',
    padding: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  bookServiceConfirmLabel: {
    color: '#2D4360',
    fontSize: 12,
    letterSpacing: 1.2,
    marginBottom: 6,
  },
  bookServiceConfirmValue: {
    color: '#0F1F3A',
    fontSize: 34,
    fontWeight: '800',
  },
  bookServiceCopyButton: {
    width: 58,
    height: 58,
    borderRadius: 12,
    backgroundColor: '#EEF2F7',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bookServiceBreakdownTitle: {
    color: '#0F1F3A',
    fontSize: 17,
    fontWeight: '800',
    marginBottom: 12,
  },
  bookServiceBreakdownCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#D8E0EB',
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  bookServiceBreakdownCardDark: {
    backgroundColor: '#12263F',
    borderColor: '#12263F',
  },
  bookServiceBreakdownCardColumn: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#D8E0EB',
    padding: 16,
    marginBottom: 12,
  },
  bookServiceBreakdownRowTop: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  bookServiceBreakdownIconWrap: {
    width: 56,
    height: 56,
    borderRadius: 10,
    backgroundColor: '#D8E6F8',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  bookServiceBreakdownIconWrapDark: {
    backgroundColor: '#2B3F57',
  },
  bookServiceBreakdownIconWrapMuted: {
    width: 56,
    height: 56,
    borderRadius: 10,
    backgroundColor: '#EDF1F6',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  bookServiceBreakdownContent: {
    flex: 1,
  },
  bookServiceBreakdownLabel: {
    color: '#2D4360',
    fontSize: 13,
    marginBottom: 4,
  },
  bookServiceBreakdownValue: {
    color: '#0F1F3A',
    fontSize: 16,
    fontWeight: '800',
  },
  bookServiceBreakdownLabelDark: {
    color: '#B6C6DA',
    fontSize: 13,
    marginBottom: 4,
  },
  bookServiceBreakdownValueDark: {
    color: '#FFFFFF',
    fontSize: 22,
    fontWeight: '800',
  },
  bookServiceServiceTagsWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 4,
  },
  bookServiceServiceTag: {
    borderRadius: 999,
    backgroundColor: '#EAF0F7',
    paddingHorizontal: 12,
    paddingVertical: 6,
    marginRight: 8,
    marginBottom: 8,
  },
  bookServiceServiceTagText: {
    color: '#2A3F5A',
    fontSize: 13,
    fontWeight: '500',
  },
  bookServiceDateTimeCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#D8E0EB',
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 14,
  },
  bookServiceDateTimeBlock: {
    flex: 1,
  },
  bookServiceDateTimeDivider: {
    width: 1,
    height: 36,
    backgroundColor: '#D8E0EB',
    marginHorizontal: 14,
  },
  bookServiceDateTimeValue: {
    color: '#0F1F3A',
    fontSize: 16,
    fontWeight: '800',
  },
  bookServiceMapCard: {
    height: 150,
    borderRadius: 16,
    backgroundColor: '#D9DEE5',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 14,
    overflow: 'hidden',
  },
  bookServiceStepThreePrimaryButtonText: {
    marginLeft: 10,
  },
  bookServiceStepThreeSecondaryButton: {
    minHeight: 62,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#D8E0EB',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    marginTop: 10,
    marginBottom: 24,
  },
  bookServiceStepThreeSecondaryButtonText: {
    marginLeft: 10,
    color: '#0F1F3A',
    fontSize: 17,
    fontWeight: '700',
  },
  logoutModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 31, 58, 0.5)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoutModalContent: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    paddingHorizontal: 24,
    paddingVertical: 32,
    alignItems: 'center',
    width: '85%',
    maxWidth: 320,
    shadowColor: '#000',
    shadowOpacity: 0.15,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
  },
  logoutModalIconWrap: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: '#FEE2E2',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
  },
  logoutModalTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#0F1F3A',
    marginBottom: 10,
    textAlign: 'center',
  },
  logoutModalMessage: {
    fontSize: 15,
    color: '#64748B',
    textAlign: 'center',
    marginBottom: 28,
    lineHeight: 22,
  },
  logoutModalButtonsRow: {
    flexDirection: 'row',
    gap: 12,
    width: '100%',
  },
  logoutModalCancelButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F1F5F9',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  logoutModalCancelButtonText: {
    color: '#475569',
    fontSize: 14,
    fontWeight: '700',
  },
  logoutModalConfirmButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#EF4444',
  },
  logoutModalConfirmButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '700',
  },

});
